import { useForm } from 'react-hook-form';
import { valibotResolver } from '@hookform/resolvers/valibot';
import * as v from 'valibot';
import { FormField, Input, Textarea } from '../ui/FormField';
import { FormOverlay } from '../ui/Spinner';

// Local form schema that includes auto-generate checkbox (not part of API request)
const AddRepositoryFormLocalSchema = v.pipe(
  v.object({
    path: v.pipe(v.string(), v.trim(), v.minLength(1, 'Path is required')),
    description: v.optional(v.pipe(v.string(), v.trim())),
    autoGenerateDescription: v.boolean(),
  }),
  v.forward(
    v.check(
      (data) => data.autoGenerateDescription || (!!data.description && data.description.length > 0),
      'Description is required when auto-generate is not selected'
    ),
    ['description']
  )
);

type AddRepositoryFormData = v.InferOutput<typeof AddRepositoryFormLocalSchema>;

export interface AddRepositoryFormSubmitData {
  path: string;
  description?: string;
  autoGenerateDescription: boolean;
}

export interface AddRepositoryFormProps {
  isPending: boolean;
  onSubmit: (data: AddRepositoryFormSubmitData) => Promise<void>;
  onCancel: () => void;
}

export function AddRepositoryForm({
  isPending,
  onSubmit,
  onCancel,
}: AddRepositoryFormProps) {
  const {
    register,
    handleSubmit,
    watch,
    setError,
    formState: { errors },
  } = useForm<AddRepositoryFormData>({
    resolver: valibotResolver(AddRepositoryFormLocalSchema),
    defaultValues: {
      path: '',
      description: '',
      autoGenerateDescription: true,
    },
    mode: 'onBlur',
  });

  const autoGenerate = watch('autoGenerateDescription');

  const handleFormSubmit = async (data: AddRepositoryFormData) => {
    try {
      await onSubmit({
        path: data.path,
        description: data.autoGenerateDescription ? undefined : data.description,
        autoGenerateDescription: data.autoGenerateDescription,
      });
    } catch (err) {
      setError('root', {
        message: err instanceof Error ? err.message : 'Failed to register repository',
      });
    }
  };

  return (
    <div className="relative card mb-5">
      <FormOverlay isVisible={isPending} message="Adding repository..." />
      <h2 className="mb-3 text-lg font-medium">Add Repository</h2>
      <form onSubmit={handleSubmit(handleFormSubmit)}>
        <fieldset disabled={isPending} className="flex flex-col gap-4">
          <FormField error={errors.path}>
            <Input
              {...register('path')}
              placeholder="Repository path (e.g., /path/to/repo)"
              error={errors.path}
            />
          </FormField>

          <div className="flex items-center gap-2">
            <input
              {...register('autoGenerateDescription')}
              type="checkbox"
              id="auto-generate-description"
              className="h-4 w-4 rounded border-slate-600 bg-slate-800 text-indigo-500 focus:ring-indigo-500 focus:ring-offset-slate-900"
            />
            <label htmlFor="auto-generate-description" className="text-sm text-gray-400">
              Auto-generate description from README
            </label>
          </div>

          <FormField label="Description" error={errors.description}>
            <Textarea
              {...register('description')}
              placeholder="Brief description of the repository"
              rows={3}
              className="text-sm"
              disabled={autoGenerate}
              error={errors.description}
            />
          </FormField>

          {errors.root && (
            <p className="text-sm text-red-400" role="alert">{errors.root.message}</p>
          )}

          <div className="flex gap-2">
            <button
              type="submit"
              className="btn btn-primary"
            >
              Add
            </button>
            <button
              type="button"
              onClick={onCancel}
              className="btn btn-danger"
            >
              Cancel
            </button>
          </div>
        </fieldset>
      </form>
    </div>
  );
}
