/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentsIndexRouteImport } from './routes/agents/index'
import { Route as SessionsSessionIdRouteImport } from './routes/sessions/$sessionId'
import { Route as AgentsAgentIdIndexRouteImport } from './routes/agents/$agentId/index'
import { Route as AgentsAgentIdEditRouteImport } from './routes/agents/$agentId/edit'

const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIndexRoute = AgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsSessionIdRoute = SessionsSessionIdRouteImport.update({
  id: '/sessions/$sessionId',
  path: '/sessions/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsAgentIdIndexRoute = AgentsAgentIdIndexRouteImport.update({
  id: '/agents/$agentId/',
  path: '/agents/$agentId/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsAgentIdEditRoute = AgentsAgentIdEditRouteImport.update({
  id: '/agents/$agentId/edit',
  path: '/agents/$agentId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/maintenance': typeof MaintenanceRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/agents': typeof AgentsIndexRoute
  '/agents/$agentId/edit': typeof AgentsAgentIdEditRoute
  '/agents/$agentId': typeof AgentsAgentIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/maintenance': typeof MaintenanceRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/agents': typeof AgentsIndexRoute
  '/agents/$agentId/edit': typeof AgentsAgentIdEditRoute
  '/agents/$agentId': typeof AgentsAgentIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/maintenance': typeof MaintenanceRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/agents/': typeof AgentsIndexRoute
  '/agents/$agentId/edit': typeof AgentsAgentIdEditRoute
  '/agents/$agentId/': typeof AgentsAgentIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/maintenance'
    | '/sessions/$sessionId'
    | '/agents'
    | '/agents/$agentId/edit'
    | '/agents/$agentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/maintenance'
    | '/sessions/$sessionId'
    | '/agents'
    | '/agents/$agentId/edit'
    | '/agents/$agentId'
  id:
    | '__root__'
    | '/'
    | '/maintenance'
    | '/sessions/$sessionId'
    | '/agents/'
    | '/agents/$agentId/edit'
    | '/agents/$agentId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MaintenanceRoute: typeof MaintenanceRoute
  SessionsSessionIdRoute: typeof SessionsSessionIdRoute
  AgentsIndexRoute: typeof AgentsIndexRoute
  AgentsAgentIdEditRoute: typeof AgentsAgentIdEditRoute
  AgentsAgentIdIndexRoute: typeof AgentsAgentIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/': {
      id: '/agents/'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$sessionId': {
      id: '/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof SessionsSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$agentId/': {
      id: '/agents/$agentId/'
      path: '/agents/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof AgentsAgentIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$agentId/edit': {
      id: '/agents/$agentId/edit'
      path: '/agents/$agentId/edit'
      fullPath: '/agents/$agentId/edit'
      preLoaderRoute: typeof AgentsAgentIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MaintenanceRoute: MaintenanceRoute,
  SessionsSessionIdRoute: SessionsSessionIdRoute,
  AgentsIndexRoute: AgentsIndexRoute,
  AgentsAgentIdEditRoute: AgentsAgentIdEditRoute,
  AgentsAgentIdIndexRoute: AgentsAgentIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
