/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as JobsIndexRouteImport } from './routes/jobs/index'
import { Route as AgentsIndexRouteImport } from './routes/agents/index'
import { Route as SettingsRepositoriesRouteImport } from './routes/settings/repositories'
import { Route as SessionsSessionIdIndexRouteImport } from './routes/sessions/$sessionId/index'
import { Route as JobsJobIdIndexRouteImport } from './routes/jobs/$jobId/index'
import { Route as AgentsAgentIdIndexRouteImport } from './routes/agents/$agentId/index'
import { Route as SessionsSessionIdWorkerIdRouteImport } from './routes/sessions/$sessionId/$workerId'
import { Route as AgentsAgentIdEditRouteImport } from './routes/agents/$agentId/edit'

const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIndexRoute = AgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRepositoriesRoute = SettingsRepositoriesRouteImport.update({
  id: '/settings/repositories',
  path: '/settings/repositories',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsSessionIdIndexRoute = SessionsSessionIdIndexRouteImport.update({
  id: '/sessions/$sessionId/',
  path: '/sessions/$sessionId/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdIndexRoute = JobsJobIdIndexRouteImport.update({
  id: '/jobs/$jobId/',
  path: '/jobs/$jobId/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsAgentIdIndexRoute = AgentsAgentIdIndexRouteImport.update({
  id: '/agents/$agentId/',
  path: '/agents/$agentId/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsSessionIdWorkerIdRoute =
  SessionsSessionIdWorkerIdRouteImport.update({
    id: '/sessions/$sessionId/$workerId',
    path: '/sessions/$sessionId/$workerId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AgentsAgentIdEditRoute = AgentsAgentIdEditRouteImport.update({
  id: '/agents/$agentId/edit',
  path: '/agents/$agentId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/maintenance': typeof MaintenanceRoute
  '/settings/repositories': typeof SettingsRepositoriesRoute
  '/agents': typeof AgentsIndexRoute
  '/jobs': typeof JobsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/agents/$agentId/edit': typeof AgentsAgentIdEditRoute
  '/sessions/$sessionId/$workerId': typeof SessionsSessionIdWorkerIdRoute
  '/agents/$agentId': typeof AgentsAgentIdIndexRoute
  '/jobs/$jobId': typeof JobsJobIdIndexRoute
  '/sessions/$sessionId': typeof SessionsSessionIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/maintenance': typeof MaintenanceRoute
  '/settings/repositories': typeof SettingsRepositoriesRoute
  '/agents': typeof AgentsIndexRoute
  '/jobs': typeof JobsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/agents/$agentId/edit': typeof AgentsAgentIdEditRoute
  '/sessions/$sessionId/$workerId': typeof SessionsSessionIdWorkerIdRoute
  '/agents/$agentId': typeof AgentsAgentIdIndexRoute
  '/jobs/$jobId': typeof JobsJobIdIndexRoute
  '/sessions/$sessionId': typeof SessionsSessionIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/maintenance': typeof MaintenanceRoute
  '/settings/repositories': typeof SettingsRepositoriesRoute
  '/agents/': typeof AgentsIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/agents/$agentId/edit': typeof AgentsAgentIdEditRoute
  '/sessions/$sessionId/$workerId': typeof SessionsSessionIdWorkerIdRoute
  '/agents/$agentId/': typeof AgentsAgentIdIndexRoute
  '/jobs/$jobId/': typeof JobsJobIdIndexRoute
  '/sessions/$sessionId/': typeof SessionsSessionIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/maintenance'
    | '/settings/repositories'
    | '/agents'
    | '/jobs'
    | '/settings'
    | '/agents/$agentId/edit'
    | '/sessions/$sessionId/$workerId'
    | '/agents/$agentId'
    | '/jobs/$jobId'
    | '/sessions/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/maintenance'
    | '/settings/repositories'
    | '/agents'
    | '/jobs'
    | '/settings'
    | '/agents/$agentId/edit'
    | '/sessions/$sessionId/$workerId'
    | '/agents/$agentId'
    | '/jobs/$jobId'
    | '/sessions/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/maintenance'
    | '/settings/repositories'
    | '/agents/'
    | '/jobs/'
    | '/settings/'
    | '/agents/$agentId/edit'
    | '/sessions/$sessionId/$workerId'
    | '/agents/$agentId/'
    | '/jobs/$jobId/'
    | '/sessions/$sessionId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MaintenanceRoute: typeof MaintenanceRoute
  SettingsRepositoriesRoute: typeof SettingsRepositoriesRoute
  AgentsIndexRoute: typeof AgentsIndexRoute
  JobsIndexRoute: typeof JobsIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  AgentsAgentIdEditRoute: typeof AgentsAgentIdEditRoute
  SessionsSessionIdWorkerIdRoute: typeof SessionsSessionIdWorkerIdRoute
  AgentsAgentIdIndexRoute: typeof AgentsAgentIdIndexRoute
  JobsJobIdIndexRoute: typeof JobsJobIdIndexRoute
  SessionsSessionIdIndexRoute: typeof SessionsSessionIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/': {
      id: '/agents/'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/repositories': {
      id: '/settings/repositories'
      path: '/settings/repositories'
      fullPath: '/settings/repositories'
      preLoaderRoute: typeof SettingsRepositoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$sessionId/': {
      id: '/sessions/$sessionId/'
      path: '/sessions/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof SessionsSessionIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId/': {
      id: '/jobs/$jobId/'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof JobsJobIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$agentId/': {
      id: '/agents/$agentId/'
      path: '/agents/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof AgentsAgentIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$sessionId/$workerId': {
      id: '/sessions/$sessionId/$workerId'
      path: '/sessions/$sessionId/$workerId'
      fullPath: '/sessions/$sessionId/$workerId'
      preLoaderRoute: typeof SessionsSessionIdWorkerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$agentId/edit': {
      id: '/agents/$agentId/edit'
      path: '/agents/$agentId/edit'
      fullPath: '/agents/$agentId/edit'
      preLoaderRoute: typeof AgentsAgentIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MaintenanceRoute: MaintenanceRoute,
  SettingsRepositoriesRoute: SettingsRepositoriesRoute,
  AgentsIndexRoute: AgentsIndexRoute,
  JobsIndexRoute: JobsIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  AgentsAgentIdEditRoute: AgentsAgentIdEditRoute,
  SessionsSessionIdWorkerIdRoute: SessionsSessionIdWorkerIdRoute,
  AgentsAgentIdIndexRoute: AgentsAgentIdIndexRoute,
  JobsJobIdIndexRoute: JobsJobIdIndexRoute,
  SessionsSessionIdIndexRoute: SessionsSessionIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
