import { useRef, useState, useEffect, useCallback, type ReactNode } from 'react';
import { useForm } from 'react-hook-form';
import { valibotResolver } from '@hookform/resolvers/valibot';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { FormField, Input, Textarea } from '../ui/FormField';
import { AgentSelector, useResolvedAgentId } from '../AgentSelector';
import { Spinner } from '../ui/Spinner';
import type { CreateWorktreeFormData } from '../../schemas/worktree-form';
import { CreateWorktreeFormSchema } from '../../schemas/worktree-form';
import type {
  CreateWorktreePromptRequest,
  CreateWorktreeCustomRequest,
  CreateWorktreeExistingRequest,
} from '@agent-console/shared';
import { refreshDefaultBranch, getRemoteBranchStatus } from '../../lib/api';
import { branchKeys } from '../../lib/query-keys';

/**
 * Worktree creation parameters without taskId.
 * The taskId is generated by the caller (Dashboard) before sending to the API.
 *
 * Note: We need to explicitly define the union type because Omit<UnionType, 'key'>
 * doesn't preserve the discriminated union structure properly.
 */
export type CreateWorktreeFormRequest =
  | Omit<CreateWorktreePromptRequest, 'taskId'>
  | Omit<CreateWorktreeCustomRequest, 'taskId'>
  | Omit<CreateWorktreeExistingRequest, 'taskId'>;

/** Values to pre-fill the form with (e.g., from a fetched GitHub Issue).
 *  Applied once on mount. When provided, draft restoration is skipped. */
export interface CreateWorktreeFormPrefill {
  initialPrompt?: string;
  sessionTitle?: string;
  branchNameMode?: 'prompt' | 'custom' | 'existing';
}

export interface CreateWorktreeFormProps {
  repositoryId: string;
  defaultBranch: string;
  defaultAgentId?: string | null;
  onSubmit: (request: CreateWorktreeFormRequest) => Promise<void>;
  onCancel: () => void;
  /** When provided, form values are persisted to localStorage under this key.
   *  On mount, saved values are restored. On successful submit, the draft is cleared. */
  draftKey?: string;
  /** Hide the form heading (useful when rendered inside a dialog with its own title) */
  hideTitle?: boolean;
  /** Optional slot rendered before the Agent selector in the header row */
  headerSlot?: ReactNode;
  /** Values to pre-fill the form with. When provided, draft restoration is skipped. */
  prefillValues?: CreateWorktreeFormPrefill;
}

export function CreateWorktreeForm({
  repositoryId,
  defaultBranch,
  defaultAgentId,
  onSubmit,
  onCancel,
  draftKey,
  hideTitle,
  headerSlot,
  prefillValues,
}: CreateWorktreeFormProps) {
  const {
    register,
    handleSubmit,
    getValues,
    setError,
    watch,
    setValue,
    reset,
    formState: { errors, dirtyFields },
  } = useForm<CreateWorktreeFormData>({
    resolver: valibotResolver(CreateWorktreeFormSchema),
    defaultValues: {
      branchNameMode: prefillValues?.branchNameMode ?? 'prompt',
      initialPrompt: prefillValues?.initialPrompt ?? '',
      githubIssue: '',
      customBranch: '',
      baseBranch: '',
      sessionTitle: prefillValues?.sessionTitle ?? '',
      agentId: defaultAgentId ?? undefined,
    },
    mode: 'onBlur',
    shouldUnregister: true,
  });

  // Draft persistence: restore saved values on mount, save on change, clear on successful submit
  // Tracks whether draft was cleared (e.g., after successful submit) to skip unmount save
  const draftClearedRef = useRef(false);

  // Ref to access dirtyFields inside effects without re-triggering them
  const dirtyFieldsRef = useRef(dirtyFields);
  dirtyFieldsRef.current = dirtyFields;

  /** Pick only user-modified fields from form values, so props-derived defaults
   *  (e.g., agentId from server) are not persisted and can update between sessions. */
  const pickDirtyValues = useCallback((values: Record<string, unknown>): Record<string, unknown> => {
    const dirty = dirtyFieldsRef.current;
    const result: Record<string, unknown> = {};
    for (const key of Object.keys(values)) {
      if (dirty[key as keyof typeof dirty]) {
        result[key] = values[key];
      }
    }
    return result;
  }, []);

  // Restore draft on mount (skipped when prefillValues is provided)
  useEffect(() => {
    if (!draftKey) return;
    if (prefillValues) return; // Skip draft restore when prefilling from issue
    draftClearedRef.current = false;
    try {
      const saved = localStorage.getItem(draftKey);
      if (saved) {
        const draft = JSON.parse(saved) as Partial<CreateWorktreeFormData>;
        // getValues() returns initial defaults (form just mounted).
        // The draft overwrites them with previously saved user input.
        reset({ ...getValues(), ...draft }, { keepDefaultValues: true });
      }
    } catch {
      // Ignore corrupted drafts
    }
    // reset and getValues are stable refs from react-hook-form
  }, [draftKey, reset, getValues, prefillValues]);



  // Save draft on form changes (debounced) and on unmount
  useEffect(() => {
    if (!draftKey) return;
    let timeoutId: ReturnType<typeof setTimeout>;
    const subscription = watch((value) => {
      clearTimeout(timeoutId);
      timeoutId = setTimeout(() => {
        try {
          localStorage.setItem(draftKey, JSON.stringify(pickDirtyValues(value as Record<string, unknown>)));
        } catch {
          // Ignore storage errors (e.g., quota exceeded)
        }
      }, 500);
    });
    return () => {
      clearTimeout(timeoutId);
      // Save current values on unmount — but skip if draft was already cleared (successful submit)
      if (!draftClearedRef.current) {
        try {
          localStorage.setItem(draftKey, JSON.stringify(pickDirtyValues(getValues() as Record<string, unknown>)));
        } catch {
          // Ignore storage errors
        }
      }
      subscription.unsubscribe();
    };
    // getValues is a stable ref from react-hook-form; pickDirtyValues is stable via useCallback
  }, [draftKey, watch, getValues, pickDirtyValues]);

  const clearDraft = useCallback(() => {
    if (draftKey) {
      draftClearedRef.current = true;
      localStorage.removeItem(draftKey);
    }
  }, [draftKey]);

  const agentId = watch('agentId');
  const resolvedAgentId = useResolvedAgentId(agentId, defaultAgentId ?? undefined);

  const branchNameMode = watch('branchNameMode');
  const initialPrompt = watch('initialPrompt');

  // Local state for refreshed default branch (overrides prop when set)
  const [refreshedDefaultBranch, setRefreshedDefaultBranch] = useState<string | null>(null);
  const effectiveDefaultBranch = refreshedDefaultBranch ?? defaultBranch;

  const queryClient = useQueryClient();

  // Mutation to refresh default branch from remote
  const refreshDefaultBranchMutation = useMutation({
    mutationFn: () => refreshDefaultBranch(repositoryId),
    onSuccess: (data) => {
      setRefreshedDefaultBranch(data.defaultBranch);
      // Invalidate remote status cache when default branch changes
      queryClient.invalidateQueries({
        queryKey: branchKeys.remoteStatusRoot(repositoryId),
        exact: false,
      });
    },
  });

  // The actual base branch to use (user input or effective default)
  const baseBranch = watch('baseBranch');
  const actualBaseBranch = baseBranch?.trim() || effectiveDefaultBranch;

  // Query for remote branch status (only when not using existing branch mode)
  const remoteStatusQuery = useQuery({
    queryKey: branchKeys.remoteStatus(repositoryId, actualBaseBranch),
    queryFn: () => getRemoteBranchStatus(repositoryId, actualBaseBranch),
    enabled: branchNameMode !== 'existing' && !!actualBaseBranch,
    staleTime: 30 * 1000, // Consider stale after 30 seconds
    retry: false, // Don't retry on failure (e.g., network issues)
  });

  const buildRequest = (data: CreateWorktreeFormData, useRemote: boolean): CreateWorktreeFormRequest => {
    switch (data.branchNameMode) {
      case 'prompt':
        return {
          mode: 'prompt',
          initialPrompt: data.initialPrompt!.trim(),
          baseBranch: data.baseBranch?.trim() || undefined,
          autoStartSession: true,
          agentId: resolvedAgentId,
          title: data.sessionTitle?.trim() || undefined,
          useRemote,
        };
      case 'custom':
        return {
          mode: 'custom',
          branch: data.customBranch!.trim(),
          baseBranch: data.baseBranch?.trim() || undefined,
          autoStartSession: true,
          agentId: resolvedAgentId,
          initialPrompt: data.initialPrompt?.trim() || undefined,
          title: data.sessionTitle?.trim() || undefined,
          useRemote,
        };
      case 'existing':
        return {
          mode: 'existing',
          branch: data.customBranch!.trim(),
          autoStartSession: true,
          agentId: resolvedAgentId,
          initialPrompt: data.initialPrompt?.trim() || undefined,
          title: data.sessionTitle?.trim() || undefined,
        };
    }
    // Exhaustiveness check - compile error if new mode is added
    const _exhaustive: never = data.branchNameMode;
    throw new Error(`Unhandled branch mode: ${_exhaustive}`);
  };

  const submitWithRemote = async (data: CreateWorktreeFormData, useRemote: boolean) => {
    try {
      const request = buildRequest(data, useRemote);
      await onSubmit(request);
      clearDraft();
    } catch (err) {
      setError('root', {
        message: err instanceof Error ? err.message : 'Failed to create worktree',
      });
    }
  };

  // Handler for normal form submit (Create button)
  const handleFormSubmit = async (data: CreateWorktreeFormData) => {
    await submitWithRemote(data, false);
  };

  // Handler for Fetch & Create button
  const handleFetchAndCreate = () => {
    handleSubmit((data) => submitWithRemote(data, true))();
  };

  return (
    <div className="relative bg-slate-800 p-3 rounded mb-4 overflow-hidden">
      {!hideTitle && <h3 className="text-sm font-medium mb-2">Create Worktree</h3>}
      <form onSubmit={handleSubmit(handleFormSubmit)}>
        <fieldset className="flex flex-col gap-2">
          <div className="flex items-center flex-wrap gap-2">
            {headerSlot}
            <div className="flex items-center gap-2 min-w-0">
              <span className="text-sm text-gray-400">Agent:</span>
              <AgentSelector
                value={resolvedAgentId}
                onChange={(value) => setValue('agentId', value, { shouldDirty: true })}
                priorityAgentId={defaultAgentId ?? undefined}
              />
            </div>
          </div>

          {/* Two-column layout for form fields */}
          <div className="grid grid-cols-1 md:grid-cols-[3fr_2fr] gap-x-4 gap-y-2">
            {/* Left column: prompt and title */}
            <div className="flex flex-col gap-2">
              {/* Initial prompt input (available for all modes) */}
              <FormField label="Initial prompt (optional)" error={errors.initialPrompt}>
                <Textarea
                  {...register('initialPrompt')}
                  placeholder="What do you want to work on? (e.g., 'Add a dark mode toggle to the settings page')"
                  className="w-full min-h-[80px] resize-y"
                  rows={3}
                  error={errors.initialPrompt}
                />
              </FormField>

              {/* Session title input */}
              <FormField label="Title (optional)" error={errors.sessionTitle}>
                <Input
                  {...register('sessionTitle')}
                  placeholder="Session title"
                  className="w-full"
                  error={errors.sessionTitle}
                />
                {initialPrompt?.trim() && (
                  <p className="text-xs text-gray-500 mt-1">Leave empty to generate from prompt</p>
                )}
              </FormField>
            </div>

            {/* Right column: branch settings */}
            <div className="flex flex-col gap-2">
              {/* Branch name mode selection */}
              <fieldset className="flex flex-col gap-0.5 border-0 p-0 m-0">
                <legend className="text-sm text-gray-400 mb-0.5">Branch name:</legend>
                <label className={`text-sm flex items-center gap-2 ${!initialPrompt?.trim() ? 'text-gray-600' : 'text-gray-400'}`}>
                  <input
                    {...register('branchNameMode')}
                    type="radio"
                    value="prompt"
                    disabled={!initialPrompt?.trim()}
                  />
                  Auto-generate
                </label>
                <label className="text-sm text-gray-400 flex items-center gap-2">
                  <input
                    {...register('branchNameMode')}
                    type="radio"
                    value="custom"
                  />
                  Custom name (new branch)
                </label>
                <label className="text-sm text-gray-400 flex items-center gap-2">
                  <input
                    {...register('branchNameMode')}
                    type="radio"
                    value="existing"
                  />
                  Use existing branch
                </label>
              </fieldset>

              {/* Branch name input (only for custom/existing) */}
              {(branchNameMode === 'custom' || branchNameMode === 'existing') && (
                <FormField error={errors.customBranch}>
                  <Input
                    {...register('customBranch')}
                    placeholder={branchNameMode === 'custom' ? 'New branch name' : 'Existing branch name'}
                    error={errors.customBranch}
                  />
                </FormField>
              )}

              {/* Base branch input (only for new branches) */}
              {branchNameMode !== 'existing' && (
                <FormField error={errors.baseBranch}>
                  <div className="flex gap-2">
                    <Input
                      {...register('baseBranch')}
                      placeholder={`Base branch (default: ${effectiveDefaultBranch})`}
                      error={errors.baseBranch}
                      className="flex-1"
                    />
                    <button
                      type="button"
                      onClick={() => refreshDefaultBranchMutation.mutate()}
                      disabled={refreshDefaultBranchMutation.isPending}
                      className="btn bg-slate-600 hover:bg-slate-500 text-sm shrink-0"
                      title="Refresh default branch from remote"
                    >
                      {refreshDefaultBranchMutation.isPending ? (
                        <Spinner size="sm" />
                      ) : (
                        'Refresh'
                      )}
                    </button>
                  </div>
                  {refreshDefaultBranchMutation.isError && (
                    <p className="text-xs text-red-400 mt-1">
                      {refreshDefaultBranchMutation.error instanceof Error
                        ? refreshDefaultBranchMutation.error.message
                        : 'Failed to refresh default branch'}
                    </p>
                  )}
                  {refreshedDefaultBranch && !refreshDefaultBranchMutation.isError && (
                    <p className="text-xs text-green-400 mt-1">
                      Default branch updated to: {refreshedDefaultBranch}
                    </p>
                  )}
                  {/* Remote branch status - fixed height to prevent layout shift */}
                  <div className="min-h-5 mt-1">
                    {remoteStatusQuery.isLoading && (
                      <div className="text-xs text-gray-400 flex items-center gap-1">
                        <Spinner size="sm" />
                        <span>Checking remote status...</span>
                      </div>
                    )}
                    {remoteStatusQuery.isError && (
                      <p className="text-xs text-yellow-400">
                        Could not check remote status (will use local branch)
                      </p>
                    )}
                    {remoteStatusQuery.data && remoteStatusQuery.data.behind > 0 && (
                      <p className="text-xs text-yellow-400">
                        ⚠️ {remoteStatusQuery.data.behind} commit{remoteStatusQuery.data.behind > 1 ? 's' : ''} behind origin/{actualBaseBranch}
                      </p>
                    )}
                  </div>
                </FormField>
              )}
            </div>
          </div>

          {errors.root && (
            <p className="text-sm text-red-400" role="alert">{errors.root.message}</p>
          )}

          <div className="flex justify-between items-center">
            {/* Left side - Fetch & Create (only when behind) */}
            <div>
              {branchNameMode !== 'existing' && remoteStatusQuery.data && remoteStatusQuery.data.behind > 0 && (
                <button
                  type="button"
                  onClick={handleFetchAndCreate}
                  className="btn bg-indigo-600 hover:bg-indigo-500 text-sm"
                  title={`Create worktree from origin/${actualBaseBranch} (latest remote)`}
                >
                  Fetch & Create
                </button>
              )}
            </div>

            {/* Right side - Cancel and Create (always visible) */}
            <div className="flex gap-2">
              <button
                type="button"
                onClick={onCancel}
                className="btn btn-danger text-sm"
              >
                Cancel
              </button>
              <button
                type="submit"
                className="btn btn-primary text-sm"
              >
                Create & Start Session
              </button>
            </div>
          </div>
        </fieldset>
      </form>
    </div>
  );
}
