import { describe, it, expect, mock, afterEach } from 'bun:test';
import { render, screen, waitFor, cleanup } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { RegisterExistingPathForm } from '../RegisterExistingPathForm';

afterEach(() => {
  cleanup();
});

function renderForm(props: Partial<React.ComponentProps<typeof RegisterExistingPathForm>> = {}) {
  const defaultProps = {
    isPending: false,
    onSubmit: mock(() => Promise.resolve()),
    onCancel: mock(() => {}),
  };
  const merged = { ...defaultProps, ...props };
  return {
    ...render(<RegisterExistingPathForm {...merged} />),
    props: merged,
  };
}

describe('RegisterExistingPathForm', () => {
  it('submits the trimmed path with autoGenerateDescription=true by default', async () => {
    const user = userEvent.setup();
    const { props } = renderForm();

    await user.type(screen.getByPlaceholderText(/Repository path/), '  /path/to/repo  ');
    await user.click(screen.getByText('Add'));

    await waitFor(() => expect(props.onSubmit).toHaveBeenCalledTimes(1));
    const submitCall = (props.onSubmit as ReturnType<typeof mock>).mock.calls[0];
    expect(submitCall[0]).toMatchObject({
      path: '/path/to/repo',
      autoGenerateDescription: true,
    });
  });

  it('blocks submit when path is empty', async () => {
    const user = userEvent.setup();
    const { props } = renderForm();

    await user.click(screen.getByText('Add'));

    await waitFor(() => expect(props.onSubmit).not.toHaveBeenCalled());
    expect(screen.getByText(/Path is required/)).toBeTruthy();
  });

  it('blocks submit when auto-generate is off and description is blank', async () => {
    const user = userEvent.setup();
    const { props } = renderForm();

    await user.type(screen.getByPlaceholderText(/Repository path/), '/path/to/repo');
    await user.click(screen.getByLabelText(/Auto-generate description/));
    await user.click(screen.getByText('Add'));

    await waitFor(() => expect(props.onSubmit).not.toHaveBeenCalled());
    expect(screen.getByText(/Description is required/)).toBeTruthy();
  });

  it('renders a root error message when onSubmit rejects', async () => {
    const user = userEvent.setup();
    const onSubmit = mock(() => Promise.reject(new Error('Repository not found')));
    renderForm({ onSubmit });

    await user.type(screen.getByPlaceholderText(/Repository path/), '/missing');
    await user.click(screen.getByText('Add'));

    await waitFor(() => {
      expect(screen.getByText('Repository not found')).toBeTruthy();
    });
  });

  it('disables interactive fields and shows overlay when isPending', () => {
    renderForm({ isPending: true });
    expect(screen.getByText('Adding repository...')).toBeTruthy();
    const pathInput = screen.getByPlaceholderText(/Repository path/);
    expect(pathInput.closest('fieldset')?.disabled).toBe(true);
  });

  it('disables description textarea when auto-generate is checked', () => {
    renderForm();
    const desc = screen.getByPlaceholderText(/Brief description/) as HTMLTextAreaElement;
    expect(desc.disabled).toBe(true);
  });

  it('enables description textarea when auto-generate is unchecked', async () => {
    const user = userEvent.setup();
    renderForm();
    await user.click(screen.getByLabelText(/Auto-generate description/));
    const desc = screen.getByPlaceholderText(/Brief description/) as HTMLTextAreaElement;
    expect(desc.disabled).toBe(false);
  });

  it('calls onCancel when Cancel is clicked', async () => {
    const user = userEvent.setup();
    const { props } = renderForm();
    await user.click(screen.getByText('Cancel'));
    expect(props.onCancel).toHaveBeenCalledTimes(1);
  });
});
