// AUTO-GENERATED by scripts/generate-schema-version.mjs — do not edit manually.
// Content hash over the wire-schema file set (packages/shared/src/schemas/*.ts).
export const SCHEMA_VERSION = '39abe2ab77eb4d46';
