// AUTO-GENERATED by scripts/generate-schema-version.mjs — do not edit manually.
// Content hash over the wire-schema file set (packages/shared/src/schemas/*.ts).
export const SCHEMA_VERSION = '3e77380424b258d3';
